### PR TITLE
Rough refactor into an IetfReview object

### PR DESCRIPTION
**Pull request by mnot**
Not complete, just wanting feedback. This is refactoring into an IetfReview object to hold the state of the review. Gets me closer to fixing #1.

I suspect there are some whitespace / newline presentation changes here, but it's hard to be sure without demo input. Any chance you could check in some `examples/` sources?

### CODE REVIEW

**Comment by larseggert** [comment]
This is great, thanks. 

I'm not sure what you mean by exampes - can't you just use any old I-D as an example?

**Comment by mnot** [comment]
I meant examples that trigger the various discusses/comments/nits, as well as with embedded discusses/comments/nits, to exercise the code and show expected output.

**Comment by larseggert** [comment]
I think I fixed the whitespace/formatting issues and will merge this now, so it doesn't keep diverging from the main branch. Feel free to fork off that again for the Markdown-review work!

**Comment by mnot** [comment]
Cool!

**Pull request merged**
